apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aoa-test
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: apps
    repoURL: 'https://github.com/nickwei8/operator-test.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true