apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-apps
spec:
  destination:
    namespace: argocd
    server: https://34.148.77.182
  source:
    path: apps
    repoURL: 'https://github.com/nickwei8/operator-test.git'
    targetRevision: HEAD
  project: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true