apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kami-library-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://34.148.77.182
  project: test
  source:
    path: overlays/staging
    repoURL: https://github.com/KamiHQ/kami-library-deploy.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 3